# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCQplVgAnbD8GwmC4OERl3_hljAaUuYM
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Performance Index calculation for membrane materials.
Works in terminal, Jupyter, and Colab.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Column handling
# ---------------------------------------------------------------------
def clean_name(name: str) -> str:
    name = str(name).strip()
    name = name.replace("₂", "2")
    name = name.replace("σ", "sigma")
    name = re.sub(r"[^A-Za-z0-9]+", "", name).lower()
    return name


def find_column(columns: list[str], aliases: list[str]) -> str | None:
    clean_map = {clean_name(col): col for col in columns}
    for alias in aliases:
        alias_clean = clean_name(alias)
        if alias_clean in clean_map:
            return clean_map[alias_clean]
    return None


def standardize_columns(df: pd.DataFrame) -> pd.DataFrame:
    material_col = find_column(df.columns.tolist(), ["Material"])
    maxtemp_col = find_column(df.columns.tolist(), ["MaxTemp", "MaxTemp_C", "Tmax", "T_max"])
    tensile_col = find_column(
        df.columns.tolist(),
        ["TensileStrength", "TensileStrength_MPa", "TensileStr", "sigma", "Strength"],
    )
    wvtr_col = find_column(
        df.columns.tolist(),
        ["WVTR", "W_v", "Wv", "WVTR_g_m2_day", "WaterVaporTransmissionRate"],
    )
    cond_col = find_column(
        df.columns.tolist(),
        ["Conductivity", "ThermalConductivity", "k", "ThermalConductivity_WmK"],
    )
    embodied_col = find_column(
        df.columns.tolist(),
        ["EmbodiedEnergy", "EmbodiedEnergy_MJ_kg", "EmbodiedE", "E"],
    )
    co2_col = find_column(
        df.columns.tolist(),
        ["CO2", "CO2Emission", "CO2Emissions", "CO_2", "CO2eq"],
    )

    required = {
        "Material": material_col,
        "MaxTemp": maxtemp_col,
        "TensileStrength": tensile_col,
        "WVTR": wvtr_col,
        "Conductivity": cond_col,
        "EmbodiedEnergy": embodied_col,
        "CO2": co2_col,
    }

    missing = [key for key, value in required.items() if value is None]
    if missing:
        raise ValueError(
            "Missing required columns: "
            + ", ".join(missing)
            + "\nAvailable columns: "
            + ", ".join(map(str, df.columns))
        )

    rename_map = {
        material_col: "Material",
        maxtemp_col: "MaxTemp",
        tensile_col: "TensileStrength",
        wvtr_col: "WVTR",
        cond_col: "Conductivity",
        embodied_col: "EmbodiedEnergy",
        co2_col: "CO2",
    }

    df = df.rename(columns=rename_map)
    return df[
        ["Material", "MaxTemp", "TensileStrength", "WVTR", "Conductivity", "EmbodiedEnergy", "CO2"]
    ].copy()


def coerce_numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype(str).str.replace(",", "", regex=False).str.replace(" ", "", regex=False),
        errors="coerce",
    )


# ---------------------------------------------------------------------
# Normalization
# ---------------------------------------------------------------------
def normalize_beneficial(series: pd.Series) -> pd.Series:
    smin, smax = series.min(), series.max()
    if pd.isna(smin) or pd.isna(smax):
        raise ValueError("Beneficial normalization failed: series contains only NaN values.")
    if np.isclose(smax, smin):
        return pd.Series(np.zeros(len(series)), index=series.index)
    return (series - smin) / (smax - smin)


def normalize_detrimental(series: pd.Series) -> pd.Series:
    smin, smax = series.min(), series.max()
    if pd.isna(smin) or pd.isna(smax):
        raise ValueError("Detrimental normalization failed: series contains only NaN values.")
    if np.isclose(smax, smin):
        return pd.Series(np.zeros(len(series)), index=series.index)
    return (smax - series) / (smax - smin)


# ---------------------------------------------------------------------
# Core performance-index calculation
# ---------------------------------------------------------------------
SCENARIOS = {
    "Equal": {
        "T_norm": 0.2,
        "sigma_norm": 0.2,
        "Wv_norm": 0.2,
        "k_norm": 0.2,
        "S_norm": 0.2,
    },
    "Flux": {
        "T_norm": 0.1,
        "sigma_norm": 0.1,
        "Wv_norm": 0.6,
        "k_norm": 0.1,
        "S_norm": 0.1,
    },
    "Sustainability": {
        "T_norm": 0.1,
        "sigma_norm": 0.1,
        "Wv_norm": 0.1,
        "k_norm": 0.1,
        "S_norm": 0.6,
    },
}


def compute_performance_indices(df_in: pd.DataFrame) -> pd.DataFrame:
    df = df_in.copy()

    df["T_norm"] = normalize_beneficial(df["MaxTemp"])
    df["sigma_norm"] = normalize_beneficial(df["TensileStrength"])
    df["Wv_norm"] = normalize_beneficial(df["WVTR"])
    df["k_norm"] = normalize_detrimental(df["Conductivity"])
    df["E_norm"] = normalize_detrimental(df["EmbodiedEnergy"])
    df["CO2_norm"] = normalize_detrimental(df["CO2"])
    df["S_norm"] = 0.5 * (df["E_norm"] + df["CO2_norm"])

    for scenario, weights in SCENARIOS.items():
        df[f"Pi_{scenario}"] = (
            weights["T_norm"] * df["T_norm"]
            + weights["sigma_norm"] * df["sigma_norm"]
            + weights["Wv_norm"] * df["Wv_norm"]
            + weights["k_norm"] * df["k_norm"]
            + weights["S_norm"] * df["S_norm"]
        )
        df[f"Rank_{scenario}"] = df[f"Pi_{scenario}"].rank(ascending=False, method="min").astype(int)

    return df


def build_comparison(df_raw: pd.DataFrame, exclude_material: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    full_df = compute_performance_indices(df_raw)

    mask = df_raw["Material"].str.upper() == exclude_material.upper()
    if mask.sum() == 0:
        raise ValueError(f"No material named '{exclude_material}' found in the Material column.")
    if mask.sum() > 1:
        raise ValueError(f"More than one row named '{exclude_material}' found in the Material column.")

    excl_df = compute_performance_indices(df_raw.loc[~mask].copy())

    full_renamed = full_df.rename(columns=lambda c: c if c == "Material" else f"{c}_full")
    excl_renamed = excl_df.rename(columns=lambda c: c if c == "Material" else f"{c}_excl")

    merged = full_renamed.merge(excl_renamed, on="Material", how="left")

    for scenario in SCENARIOS:
        merged[f"RankChange_{scenario}"] = (
            merged[f"Rank_{scenario}_full"] - merged[f"Rank_{scenario}_excl"]
        )

    return full_df, merged


# ---------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------
def load_input_file(path: Path) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix == ".csv":
        return pd.read_csv(path)
    if suffix in {".xls", ".xlsx"}:
        return pd.read_excel(path)
    raise ValueError(f"Unsupported file type for '{path}'. Use CSV, XLS, or XLSX.")


def prepare_dataframe(df_raw: pd.DataFrame) -> pd.DataFrame:
    df = standardize_columns(df_raw)
    df["Material"] = df["Material"].astype(str).str.strip()

    numeric_cols = ["MaxTemp", "TensileStrength", "WVTR", "Conductivity", "EmbodiedEnergy", "CO2"]
    for col in numeric_cols:
        df[col] = coerce_numeric(df[col])

    df = df.dropna(how="all").reset_index(drop=True)

    if df[numeric_cols].isna().any().any():
        bad_rows = df[df[numeric_cols].isna().any(axis=1)]
        raise ValueError(
            "Some required numeric cells could not be read.\nProblem rows:\n"
            + bad_rows.to_string(index=False)
        )

    return df


def pick_input_file_from_notebook() -> Path:
    try:
        from google.colab import files

        print("Upload your CSV or Excel file.")
        uploaded = files.upload()
        filename = list(uploaded.keys())[0]
        return Path(filename)
    except Exception:
        raise ValueError(
            "No valid input file was provided. In terminal, pass a CSV/XLS/XLSX path. "
            "In Colab, run without arguments and upload the file when prompted."
        )


def resolve_input_file(arg_path: Path | None) -> Path:
    valid_suffixes = {".csv", ".xls", ".xlsx"}

    if arg_path is not None and arg_path.suffix.lower() in valid_suffixes:
        return arg_path

    # Jupyter often injects a kernel .json file as a fake positional arg
    if arg_path is not None and arg_path.suffix.lower() == ".json":
        return pick_input_file_from_notebook()

    if arg_path is None:
        return pick_input_file_from_notebook()

    raise ValueError(
        f"Unsupported input file '{arg_path}'. Use CSV, XLS, or XLSX."
    )


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description="Calculate membrane-material performance indices.")
    parser.add_argument("input_file", type=Path, nargs="?", help="Path to input CSV or Excel file.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("performance_index_outputs"),
        help="Directory for output CSV files.",
    )
    parser.add_argument(
        "--exclude-material",
        type=str,
        default="SBS",
        help="Material to exclude from the normalization pool for sensitivity calculation.",
    )

    # Use only real CLI args in terminal; ignore notebook kernel args
    known_args, _ = parser.parse_known_args()

    input_file = resolve_input_file(known_args.input_file)
    output_dir = known_args.output_dir
    exclude_material = known_args.exclude_material

    output_dir.mkdir(parents=True, exist_ok=True)

    raw_df = load_input_file(input_file)
    df = prepare_dataframe(raw_df)

    full_df = compute_performance_indices(df)
    full_out = output_dir / "performance_index_full.csv"
    full_df.to_csv(full_out, index=False)

    try:
        _, comparison_df = build_comparison(df, exclude_material=exclude_material)
        comparison_out = output_dir / f"performance_index_excluding_{exclude_material}.csv"
        comparison_df.to_csv(comparison_out, index=False)
        print(f"Saved:\n- {full_out}\n- {comparison_out}")
    except ValueError as exc:
        print(f"Saved:\n- {full_out}")
        print(f"Excluded-material comparison skipped: {exc}")


if __name__ == "__main__":
    main()