# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwMyU02hKdVezDcthVK5rYAZcibPZzcj
"""

# ==========================================
# 🔬 MATERIAL PROPERTY ANALYSIS SCRIPT (with r & p-values)
# Google Colab Compatible (CSV or Excel)
# Nomenclature: Tmax, σ, Wv, k, E, Cm (upright, subscripts where needed)
# Heatmap labels bold
# ==========================================

# --- Step 1: Import Libraries ---
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from google.colab import files
import io

# Set font globally to sans-serif
plt.rcParams["font.family"] = "DejaVu Sans"

# --- Step 2: Upload File ---
print("📂 Please upload your data file (.csv or .xlsx):")
uploaded = files.upload()

# Get filename dynamically
filename = list(uploaded.keys())[0]

# Detect file type
if filename.endswith('.csv'):
    df = pd.read_csv(
        io.BytesIO(uploaded[filename]),
        encoding='utf-8',
        sep=None,         # autodetect delimiter
        engine='python'   # required for delimiter detection
    )
elif filename.endswith(('.xls', '.xlsx')):
    df = pd.read_excel(io.BytesIO(uploaded[filename]))
else:
    raise ValueError("❌ Unsupported file type. Please upload a .csv or .xlsx file.")


# --- Step 3: Clean Column Names ---
df.columns = (
    df.columns.str.strip()
    .str.replace("_", " ")
    .str.replace("-", " ")
    .str.replace(r'(?<!^)(?=[A-Z])', ' ', regex=True)
    .str.title()
)

print("📋 First 5 rows:\n")
display(df.head())

# --- Step 4: Check Missing Values ---
print("\n🧹 Checking for missing values:\n")
print(df.isnull().sum())

# --- Step 5: Rename Columns for Plotting ---
rename_map = {}
for col in df.columns:
    key = col.lower().replace(" ", "")
    if "temp" in key or "tmax" in key:
        rename_map[col] = r"T$_{\mathrm{max}}$"
    elif "tensile" in key or "strength" in key:
        rename_map[col] = "σ"
    elif "wvtr" in key or "water" in key:
        rename_map[col] = r"W$_{\mathrm{v}}$"
    elif "conduct" in key or "cond" in key:
        rename_map[col] = "k"
    elif "energy" in key:
        rename_map[col] = "E"
    elif "cost" in key or "cm" in key:
        rename_map[col] = r"C$_{\mathrm{m}}$"

df_renamed = df.rename(columns=rename_map)

# --- Step 6: Pearson Correlation and p-values ---
numeric_cols = df_renamed.select_dtypes(include=[np.number]).columns.tolist()
r_matrix = pd.DataFrame(index=numeric_cols, columns=numeric_cols, dtype=float)
p_matrix = pd.DataFrame(index=numeric_cols, columns=numeric_cols, dtype=float)

for col1 in numeric_cols:
    for col2 in numeric_cols:
        if col1 == col2:
            r_matrix.loc[col1, col2] = 1.0
            p_matrix.loc[col1, col2] = 0.0
        else:
            r, p = pearsonr(df_renamed[col1], df_renamed[col2])
            r_matrix.loc[col1, col2] = r
            p_matrix.loc[col1, col2] = p

print("\n📈 Pearson Correlation Coefficients (r):\n")
display(r_matrix)

print("\n📊 Corresponding p-values:\n")
display(p_matrix)

# --- Step 7: Heatmap of r-values ---
plt.figure(figsize=(12, 10), dpi=1800)
sns.heatmap(
    r_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    square=True,
    linewidths=0.5,
    annot_kws={"fontsize": 14}
)
plt.xticks(fontsize=14, rotation=0, fontweight='bold')  # Bold X labels
plt.yticks(fontsize=14, rotation=0, fontweight='bold')  # Bold Y labels
plt.tight_layout()
plt.show()

# --- Step 8: Top Correlations by |r| ---
corr_unstacked = r_matrix.unstack().sort_values(ascending=False)
corr_unstacked = corr_unstacked[corr_unstacked < 1]  # Remove self-correlation
top_corr = corr_unstacked.head(5)
bottom_corr = corr_unstacked.tail(5)

print("\n🔍 Top 5 strongest positive correlations:\n")
print(top_corr)

print("\n🔍 Top 5 strongest negative correlations:\n")
print(bottom_corr)

# --- Step 9: Annotated Scatterplots for Top Correlations ---
top_features = top_corr.index.tolist()
for (x, y) in top_features:
    r_val = r_matrix.loc[x, y]
    p_val = p_matrix.loc[x, y]
    plt.figure(figsize=(6,5))
    sns.regplot(x=df_renamed[x], y=df_renamed[y], scatter_kws={'s':50, 'alpha':0.7}, line_kws={"color": "red"})
    plt.title(f"{y} vs {x}\n$r = {r_val:.2f}$, $p = {p_val:.3e}$", fontsize=14)
    plt.xlabel(x, fontsize=12, fontweight='bold')
    plt.ylabel(y, fontsize=12, fontweight='bold')
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()

# --- Step 10: Save Results ---
r_matrix.to_csv("pearson_r_matrix.csv", index=True)
p_matrix.to_csv("pearson_p_matrix.csv", index=True)
print("\n💾 Results saved as 'pearson_r_matrix.csv' and 'pearson_p_matrix.csv'")
files.download("pearson_r_matrix.csv")
files.download("pearson_p_matrix.csv")

print("\n🎉 Analysis complete! You now have r-values, p-values, correlations, and plots.")